
stages:
  - stage: build
    jobs:
      - job: build
        steps:
          - script:
            displayName: lint
          - script:
            displayName: build
          - script: 
            displayName: run tests