
pool: local
stages:
  - stage: build
    displayName: Build
    jobs:
      - job: build
        steps:
          - script: npm ci
            displayName: restore
          - script: npm run build
            displayName: build
          - script: npm run pack
            displayName: pack